# Generated by Django 5.2.6 on 2026-01-28 14:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Short code (e.g., IT, HR, FIN)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SupplyCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "is_material",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, items are borrowable equipment that must be returned",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon class name (e.g., 'laptop', 'printer')",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Supply Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("gso_staff", "GSO Staff"),
                            ("department_user", "Department User"),
                        ],
                        default="department_user",
                        max_length=20,
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="core.department",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instance_code",
                    models.CharField(
                        help_text="Unique identifier (e.g., LAPTOP-01, PROJ-03)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        help_text="Manufacturer serial number",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("borrowed", "Borrowed"),
                            ("maintenance", "Under Maintenance"),
                            ("retired", "Retired"),
                            ("lost", "Lost"),
                            ("damaged", "Damaged"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "condition_notes",
                    models.TextField(
                        blank=True, help_text="Notes about current condition"
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, null=True, upload_to="qr_codes/instances/"
                    ),
                ),
                ("last_borrowed_at", models.DateTimeField(blank=True, null=True)),
                ("last_returned_at", models.DateTimeField(blank=True, null=True)),
                ("acquired_date", models.DateField(blank=True, null=True)),
                ("warranty_expiry", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_borrowed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="last_borrowed_instances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment Instance",
                "verbose_name_plural": "Equipment Instances",
                "ordering": ["supply", "instance_code"],
            },
        ),
        migrations.CreateModel(
            name="BorrowedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrowed_at", models.DateTimeField(auto_now_add=True)),
                ("return_deadline", models.DateTimeField()),
                ("returned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "return_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Return"),
                            ("good", "Returned in Good Condition"),
                            ("damaged", "Returned Damaged"),
                            ("lost", "Lost"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "return_notes",
                    models.TextField(
                        blank=True, help_text="Notes about condition upon return"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrowed_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrowed_items",
                        to="core.equipmentinstance",
                    ),
                ),
            ],
            options={
                "ordering": ["-borrowed_at"],
            },
        ),
        migrations.CreateModel(
            name="ExtensionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_days",
                    models.PositiveIntegerField(
                        help_text="Number of additional days requested"
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Reason for the extension request"),
                ),
                ("original_deadline", models.DateTimeField()),
                ("new_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                (
                    "borrowed_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension_requests",
                        to="core.borroweditem",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extension_requests_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestorBorrowerAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_requests", models.PositiveIntegerField(default=0)),
                ("approved_requests", models.PositiveIntegerField(default=0)),
                ("rejected_requests", models.PositiveIntegerField(default=0)),
                ("cancelled_requests", models.PositiveIntegerField(default=0)),
                ("total_borrows", models.PositiveIntegerField(default=0)),
                ("active_borrows", models.PositiveIntegerField(default=0)),
                ("on_time_returns", models.PositiveIntegerField(default=0)),
                ("late_returns", models.PositiveIntegerField(default=0)),
                ("total_overdue_days", models.PositiveIntegerField(default=0)),
                ("good_condition_returns", models.PositiveIntegerField(default=0)),
                ("damaged_returns", models.PositiveIntegerField(default=0)),
                ("lost_items", models.PositiveIntegerField(default=0)),
                (
                    "reliability_score",
                    models.FloatField(
                        default=100.0,
                        help_text="0-100 score based on return performance",
                    ),
                ),
                ("last_request_at", models.DateTimeField(blank=True, null=True)),
                ("last_borrow_at", models.DateTimeField(blank=True, null=True)),
                ("last_return_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Analytics",
                "verbose_name_plural": "User Analytics",
            },
        ),
        migrations.CreateModel(
            name="Supply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current stock quantity (for consumables) or total units (for equipment)",
                    ),
                ),
                (
                    "min_stock_level",
                    models.PositiveIntegerField(
                        default=5, help_text="Alert threshold for low stock"
                    ),
                ),
                (
                    "is_consumable",
                    models.BooleanField(
                        default=True,
                        help_text="If False, item must be returned after use",
                    ),
                ),
                (
                    "default_borrow_days",
                    models.PositiveIntegerField(
                        default=3, help_text="Default number of days for borrowing"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="pcs",
                        help_text="Unit of measurement (pcs, box, ream, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="supply_images/"
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, null=True, upload_to="qr_codes/supplies/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_supplies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplies",
                        to="core.supplycategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Supplies",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("damage", "Damage"),
                            ("loss", "Loss"),
                            ("theft", "Theft"),
                            ("expired", "Expired"),
                            ("correction", "Inventory Correction"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("description", models.TextField()),
                (
                    "is_penalty",
                    models.BooleanField(
                        default=False,
                        help_text="If True, this adjustment incurs a penalty",
                    ),
                ),
                (
                    "penalty_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("adjusted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "adjusted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_adjustments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "borrowed_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adjustments",
                        to="core.borroweditem",
                    ),
                ),
                (
                    "equipment_instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adjustments",
                        to="core.equipmentinstance",
                    ),
                ),
                (
                    "responsible_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_adjustments_responsible",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supply",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="core.supply",
                    ),
                ),
            ],
            options={
                "ordering": ["-adjusted_at"],
            },
        ),
        migrations.AddField(
            model_name="equipmentinstance",
            name="supply",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="core.supply",
            ),
        ),
        migrations.CreateModel(
            name="SupplyRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_code",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated request code",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "batch_group_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Groups multiple requests into a single batch",
                        null=True,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("purpose", models.TextField(help_text="Reason for the request")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("issued", "Issued"),
                            ("partially_returned", "Partially Returned"),
                            ("returned", "Returned"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "needed_by",
                    models.DateTimeField(
                        blank=True, help_text="When the item is needed", null=True
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, null=True, upload_to="qr_codes/requests/"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_instance",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific unit requested (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_requests",
                        to="core.equipmentinstance",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supply_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supply",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="core.supply",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="QRScanLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qr_data", models.CharField(max_length=255)),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("scan", "General Scan"),
                            ("issue", "Issue Item"),
                            ("return", "Return Item"),
                            ("inventory", "Inventory Check"),
                        ],
                        default="scan",
                        max_length=20,
                    ),
                ),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("was_successful", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "equipment_instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_logs",
                        to="core.equipmentinstance",
                    ),
                ),
                (
                    "scanned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qr_scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supply",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_logs",
                        to="core.supply",
                    ),
                ),
                (
                    "supply_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_logs",
                        to="core.supplyrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "QR Scan Log",
                "verbose_name_plural": "QR Scan Logs",
                "ordering": ["-scanned_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("in", "Stock In"),
                            ("out", "Stock Out"),
                            ("adjustment", "Adjustment"),
                            ("transfer", "Transfer"),
                            ("return", "Return"),
                            ("damage", "Damage Write-off"),
                            ("loss", "Loss Write-off"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(help_text="Positive for in, negative for out"),
                ),
                ("previous_quantity", models.PositiveIntegerField()),
                ("new_quantity", models.PositiveIntegerField()),
                (
                    "reference_code",
                    models.CharField(
                        blank=True,
                        help_text="PO number, request code, etc.",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "borrowed_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_transactions",
                        to="core.borroweditem",
                    ),
                ),
                (
                    "equipment_instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="core.equipmentinstance",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supply",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="core.supply",
                    ),
                ),
                (
                    "supply_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_transactions",
                        to="core.supplyrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_at"],
            },
        ),
        migrations.AddField(
            model_name="borroweditem",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrowed_items",
                to="core.supplyrequest",
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        help_text="Stored separately in case user is deleted",
                        max_length=254,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("issue", "Issue"),
                            ("return", "Return"),
                            ("scan", "Scan"),
                            ("export", "Export"),
                            ("import", "Import"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("supply", "Supply"),
                            ("category", "Category"),
                            ("instance", "Equipment Instance"),
                            ("request", "Supply Request"),
                            ("borrowed", "Borrowed Item"),
                            ("extension", "Extension Request"),
                            ("department", "Department"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "entity_repr",
                    models.CharField(
                        blank=True,
                        help_text="String representation of the entity",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        help_text="JSON diff of changes for updates",
                        null=True,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="core_auditl_user_id_969660_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="core_auditl_entity__244637_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="core_auditl_action_d80c2d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("request_approved", "Request Approved"),
                            ("request_rejected", "Request Rejected"),
                            ("item_issued", "Item Issued"),
                            ("item_due_soon", "Item Due Soon"),
                            ("item_overdue", "Item Overdue"),
                            ("extension_approved", "Extension Approved"),
                            ("extension_rejected", "Extension Rejected"),
                            ("account_approved", "Account Approved"),
                            ("account_rejected", "Account Rejected"),
                            ("new_request", "New Request"),
                            ("low_stock", "Low Stock Alert"),
                            ("system", "System Notification"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="URL to navigate when clicked",
                        max_length=255,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_borrowed_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.borroweditem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.supplyrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="core_notifi_user_id_f286cd_idx",
                    )
                ],
            },
        ),
    ]
